version: "3.8"
services:
  # api:
  #   build: ./backend
  #   container_name: backend_c
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules

  # client:
  #   build: ./frontend
  #   container_name: frontend_c
  #   ports:
  #     - "5173:5173"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - mongodb_data:/data/db

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: team-cooked
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data

  fastapi_server:
    build: ./fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_server:/app

volumes:
  mongodb_data:
  minio_data:
