version: "3.8"
services:
  # api:
  #   build: ./backend
  #   container_name: backend_c
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  # client:
  #   build: ./frontend
  #   container_name: frontend_c
  #   ports:
  #     - "5173:5173"
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod --noauth
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
